"""Package metadata for :mod:`triplecover`."""

from __future__ import annotations

from .bounds import (
    catalan,
    cover_family,
    ear_bounds,
    face_budget,
    fan,
    fan_families,
    fans_cover_types,
    lower_bound_certificate,
    max_ear_triangulation_count,
    verify_light_claims,
    verify_weight_bound,
    weights_of,
)
from .exact import ExactResult, incidence_matrix, solve_exact, solve_lp, verify_cover
from .polygon import (
    Triangulation,
    all_triples,
    crosses,
    dual_degrees,
    dual_tree,
    ear_faces,
    ears,
    face_type,
    face_type_name,
    is_boundary_edge,
    is_triangulation,
    triangulations,
)
from .triples import (
    balanced_c_triples,
    certificate_total,
    gaps,
    is_half,
    is_light,
    maxgap,
    mid_c_triples,
    phi,
    triple_type,
    weight,
)

__version__ = "1.0.0"

__all__ = [
    "Triangulation",
    "all_triples",
    "crosses",
    "dual_degrees",
    "dual_tree",
    "ear_faces",
    "ears",
    "face_type",
    "face_type_name",
    "is_boundary_edge",
    "is_triangulation",
    "triangulations",
    "catalan",
    "cover_family",
    "ear_bounds",
    "face_budget",
    "fan",
    "fan_families",
    "fans_cover_types",
    "lower_bound_certificate",
    "max_ear_triangulation_count",
    "verify_light_claims",
    "verify_weight_bound",
    "weights_of",
    "ExactResult",
    "incidence_matrix",
    "solve_exact",
    "solve_lp",
    "verify_cover",
    "balanced_c_triples",
    "certificate_total",
    "gaps",
    "is_half",
    "is_light",
    "maxgap",
    "mid_c_triples",
    "phi",
    "triple_type",
    "weight",
    "__version__",
]